### ISSUE TITLE
Notifications get off screen when panel is hidden

### ISSUE THREAD

**Issue by maverick74** [intika/kdetogglepanel#1]
as mentioned in https://github.com/intika/org.kde.plasma.notifications.full/issues/1

Notifications are partially hidden/cut when the panel is hidden 

![bug](https://user-images.githubusercontent.com/14912461/47189675-a8971080-d335-11e8-9382-7db45132e818.png)

(possible do to it being set with a negative value... setting it to 0 (zero) could possibly solve the problem...)

**Comment by intika** [comment]
i am reviewing the code to see how can i save the panel size...

as you are on plasma 5.14 the code should work without using the feature to force to unlock... i think i will need some vm to test my code on recent plasma....

i will let you know ;)

**Comment by intika** [comment]
Tested the code on a VM with plasma 5.14... 
Just released v3 everything should be solved... 
Unlocked panel is not needed with plasma > 5.12 ;)

https://www.opendesktop.org/p/1269113/ 
let me know if you have questions ;)

**Comment by maverick74** [comment]
@intika 
i've updated my version but the problem still persist! Notifications are still off screen.

here are my configs:
![configs](https://user-images.githubusercontent.com/14912461/47210414-ca6eb280-d38a-11e8-90a6-e536ff337849.png)

Also... the panel is not respecting the size specified in the configurations (isn't there a way to store the panel size in a variable (or something) before it's set to 0 to after restore it again?)

Also, it keeps unlocking the panels. It shows this message:
![unlocking](https://user-images.githubusercontent.com/14912461/47210438-da869200-d38a-11e8-819f-5775388968f5.png)

**Comment by intika** [comment]
I reviewed the code and this should not happen, something is not good on your machine... 

> Also... the panel is not respecting the size specified in the configurations (isn't there a way to store the panel size in a variable (or something) before it's set to 0 to after restore it again?)

This is hardly doable because the plasmoid is not using C++ code but only qml, panel manipulation are done via a kwin script to bypass the limitation of plasmoid.... so in short yes it's doable but require some hours of additional work that i don't have for it... 

>  Also, it keeps unlocking the panels. It shows this message:

This and others issues you have with the new versions should not happen the code is good and tested... i think you have an update issue, where version 3 is mixed with v2  

Can you please :
- Remove the widget from the taskbar
- Uninstall the widget and remove it
- Remove the folder "~/.local/share/plasma/plasmoids/com.github.intika.kdetogglepanel/"
- Reboot 
- Install the widget again, test and let me know ;)

**Comment by maverick74** [comment]
> I reviewed the code and this should not happen, something is not good on your machine...

I also thought about that possibility... probably even something related to TW constant updates...

> This is hardly doable because the plasmoid is not using C++ code but only qml panel manipulation are done via a kwin script to bypass the limitation of plasmoid.... so in short yes it's doable but require some hours of additional work that i don't have for it...

Maybe this time you get that jackpot ahahahah :P - it's not a big deal, anyway. There's a way to configure so it's fine :)

> Can you please : ...

i had done all of it just after i sent you the previous message, but i didn't reboot!

Will do it all over again now and report in a few minutes :)

**Comment by maverick74** [comment]
GREAT NEWS!!! IT WORKS!!! :D 

Still - this might be, or not, a small bug - when having its size set to 0 it blinks and shows a small "ghost" of the left side of screen.

clarifying:
I have the panel with it's size set to 300px on the right side of the screen, occupying the whole height.
Now imagine that it takes a screenshot of 300px from the whole height of the left side of the screen, shows it for a few microseconds and then shows the panel correctly!

However, this does not happen always...

**Comment by intika** [comment]
> Still - this might be, or not, a small bug - when having its size set to 0 it blinks and shows a small "ghost" of the left side of screen.

Verify that you have the setting "Working Mode - Effect" set to "Just change the size..." also when the panel is set to 0 if the panel is configured to auto-hide you will still have 1px of the panel displayed... you have to set to "Windows go below..." to make it completely invisible...

> clarifying:
I have the panel with it's size set to 300px on the right side of the screen, occupying the whole height.
Now imagine that it takes a screenshot of 300px from the whole height of the left side of the screen, shows it for a few microseconds and then shows the panel correctly!

Try editing the panel option... but i think there is not much i can do about it... plasma does not have an accessible method to hide the panel, it also does not expect a panel to be sized 0 so... lol

**Comment by maverick74** [comment]
It's not on auto-hide, but everything else is set as you said.

the funny thing is that, in "Working mode - toggle", if i use the "Use a negative value..." option this does not happen. It just happens if i use "set the panel size to 0..." option.

Naturally... this is a minor detail...

THANK YOU so much for your work!!! It's an awesome widget :D

**Comment by intika** [comment]
;) :+1: 
I did some tests, this does not happen if the panel is set to -1 instead of 0... i will correct that in next version (next month)

**Comment by maverick74** [comment]
i've been testing it with -1. It's really funny the difference that 1 small pixel does... :D

**Comment by intika** [comment]
yes i guess plasma panels are not meant to have -1 or 0 as size 
ohh great you edited the code yourself that's cool :+1:

**Comment by maverick74** [comment]
I've passed by a few programing languages already, unfortunately i didn't learn enough to be a real programmer!!!
It's something that really makes me sad because i really like it. 
...maybe someday...

About plasma, yes it seems that way. Also, not all plasmoids work well on the panel. It would be nice if some would work on the panel as they do on the desktop but again, it seems they are not meant to do that. Anyway... there is no better/powerful desktop than plasma. :)

**Comment by intika** [comment]
> there is no better/powerful desktop than plasma. :)

yes indeed 



> I've passed by a few programing languages already, unfortunately i didn't learn enough to be a real programmer!!!

you are already a programmer ! just do what you love, the most important are the basis (algorithmic) and you have it, now when it come to this or that language every dev need to learn contentiously... so just go ahead and program what you want :)

plasma could be a good start as the code is simple... here is what i do personally, when i start a new plasmoid i just pick one that is similar or close to it and edit the code to my need and when i am stuck i just work out the rest by google search lol a lot of devs do that ;)

**Comment by intika** [comment]
am preparing a new extension based on this one, it would toggle and SWITCH panels .... 
the purpose is to have 2 similar panel in the same area and switch between them :) 

why ? my task manager get full of apps when i open a lot of windows and i need a temporary panel that would display only tasks

**Comment by maverick74** [comment]
@intika thank you for your kind words. I do like programing a lot and did manage to get good grades at it (in a 0-20 scale i got 19 at C++, 18 at VB, others were around 16 such as Java ActionScript and Lingo... and the rest i can't remember the grades already...)

That new widget might be useful as well. Maybe i'll use both :D.

by the way, when you update the Toggle Panel, drop me a line. I prefer to use the one from you than the one i edited (in case i made something wrong)

I would, particularly, like to thank you for the tips on how you start a plasmoid and about what you do when you get stuck. I thought developers never need to google anything LOL and they always started from zero... Thank you for that!

**Comment by intika** [comment]
I will let you know when i release any thing that might interest you for sure... the plasmoid is ready but its just that i don't want to publish it before adding the check update function that i want to add to all my plasmoids... indeed this function would be a setting that can be disabled ;) 

So don't worry i will let you know here when i push an update or the new plasmoid... 

> I would, particularly, like to thank you for the tips on how you start a plasmoid and about what you do when you get stuck. I thought developers never need to google anything LOL and they always started from zero... Thank you for that!

When your main work require working with let say C++ and you do that all day long, indeed you became expert on c++ and you can just start from zero when you do a new project because its easier... but when you play with different language from time to time it is almost impossible to start from zero... just look at stackoverflow and all the dev questions around, every one is sharing what he know and no one know everything...   i also thought in the past that devs always start from zero but in reality just really really few do... i know that feeling when you see your teacher starting from zero a project and you start wondering "why this"/"why that"/"how you.." etc... and 99% of the time the teacher just do his stuff without really deeply explaining why he start here or there... we always forget something, teacher do that all day long so its normal that they remember 

Now in some language it is very easy to start from zero, like project done in Eclipse or VisualStudio etc... because you have a bush of tool that help you to add component all the way... 

any way... ;) see you later

**Comment by maverick74** [comment]
Hum... you gave me very nice tips :D 
Will take a more close look at stackoverflow.

Thank you for all your advice :)

**Comment by intika** [comment]
I finished my plasmoid and i reviewed fully the previous code... it works better and i am impressed with its utility it seem nothing but in my case be able to switch panel to one with a larger taskmanager is a big plus.... any way as i am not publishing it soon i will just send you a private version here in my next post :) 

For stackoverflow the site is amazing its like the bible of any dev but i have to warn you the site is like the code its very very very very organized and they tend to be super rude to new users that dont respect all the aspect of the site... you need to take almost 1 or 2 days learning their rules... but to make it short the reason is simple all devs want quality content and any one have to follow the rules...  the other reason is psychological because they up/down vote is always misunderstood, down vote does not mean your contribution is not good it mean you have to follow the rules.

any way bla bla bla lol its a pleasure to talk to you :)

Edit : File deleted...

**Comment by intika** [comment]
[com.github.intika.kdeswitchpanel.plasmoid.zip](https://github.com/intika/kdetogglepanel/files/2511655/com.github.intika.kdeswitchpanel.plasmoid.zip)
There you go ;) 
just rename it to plasmoid

**Comment by maverick74** [comment]
It's very nice to talk to you too. :)

From what i can tell Switch Panel can work as Toggle Panel. If one sets the same panel in both options it will show/hide the panel in question :) Is this intentional, or are my plasmoids conflicting with one another?

It works great, anyway :D .

There's one funny detail, however - it's not a problem with your plasmoid, I think it's a Plasma "rule" i never noticed in plasma - it does not allow a panel to cover a plasmoid! 
Even it the panel has it's height to half screen, one cannot put a plasmoid on the other "free half"... 

it's weird

**Comment by intika** [comment]
> From what i can tell Switch Panel can work as Toggle Panel. If one sets the same panel in both options it will show/hide the panel in question :) Is this intentional, or are my plasmoids conflicting with one another?

Eeeeemmmmm wait a second... the code is different... but yes indeed you are right... so you can use that awaiting i release the update... 
Note that the code for this one had been completely reviewed and optimized so its better to use what i sent you ;) by the way i deleted the file so keep a copy locally ;)  

There is no conflict it just how the code work, the code check panels over variable so he don't really know that panel1 is panel2 so you can use it like that if you want ;) 

now the only difference its when you use the timer of 10 sec... in this code the switch won't check if the panel is visible or not it will just toggle after 10 sec no matter what... 
in the other code the button does not toggle if the panel is hidden.
what i mean is the timer is there to hide the panel not to display it if it was hidden. (which will be the case here)

> There's one funny detail, however - it's not a problem with your plasmoid, I think it's a Plasma "rule" i never noticed in plasma - it does not allow a panel to cover a plasmoid!
Even it the panel has it's height to half screen, one cannot put a plasmoid on the other "free half"... 

This is normal its not a bug because panels are containers for plasmoid so they can not have the same overlay

;)

**Comment by maverick74** [comment]
Nice :) So Switch Panel is, in fact, Switch Panel AND Toggle Panel!!!
It a 2 in 1 product ahahah :D

And yes... I'll keep a backup very secure ;)

Thank you :)

**Comment by intika** [comment]
i am uploading and updating my works :) 
if you are interested here are some links :) 

https://github.com/intika/Librefox

https://github.com/Intika-Linux-Plasmoid/

https://github.com/Intika-Linux-Plasmoid/plasmoid-switch-panel

https://github.com/Intika-Linux-Plasmoid/plasmoid-toggle-panel
